name: Playwright E2E Tests
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      url:
        description: 'Base URL for test run'
        required: false
        default: ''
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.17.0
    - name: Install dependencies
      run: npm ci

    - name: Install Browsers
      run: npx playwright install --with-deps

    - name: Set PLAYWRIGHT_BASE_URL
      run: |
        if [ -n "${{ github.event.inputs.url }}" ]; then
          echo "PLAYWRIGHT_BASE_URL=${{ github.event.inputs.url }}" >> $GITHUB_ENV
        else
          echo "PLAYWRIGHT_BASE_URL=${{ secrets.PLAYWRIGHT_BASE_URL }}" >> $GITHUB_ENV
        fi
    - name: Run tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

  allure-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history