name: Playwright E2E Tests
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      url:
        description: 'Base URL for test run'
        required: false
        default: ${{ secrets.PLAYWRIGHT_BASE_URL }}
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.17.0
    - name: Install dependencies
      run: npm ci

    - name: Install Browsers
      run: npx playwright install --with-deps

    - name: Set PLAYWRIGHT_BASE_URL
      run: echo "PLAYWRIGHT_BASE_URL=${{ github.event.inputs.url}} || ${{ secrets.PLAYWRIGHT_BASE_URL }}" >> $GITHUB_ENV

    - name: Run tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7